# Bambee Garfield Project 4

Name: [Bambee Garfield](https://github.com/Bambee26)

My GitHub [Repos](https://github.com/Bambee26?tab=repositories)

## Task 1 - Series

In [7]:
## Task 1 - Series

import pandas as pd

grades = pd.Series([99, 100, 103, 98, 75])

grades.count()

grades.mean()

grades.min()

grades.max()

grades.std()

grades.describe()


count      5.000000
mean      95.000000
std       11.335784
min       75.000000
25%       98.000000
50%       99.000000
75%      100.000000
max      103.000000
dtype: float64

## Task 2 - Series from Dictionary

In [14]:
import pandas as pd
grades_dict = {'Wally': [87, 96, 70], 'Eva': [100, 87, 90],
                                  'Sam': [94, 77, 90], 'Katie': [100, 81, 82],
                                  'Bob': [83, 65, 85]}
grades = pd.DataFrame(grades_dict)

print(grades['Eva'])

print(grades.Wally)

print(grades.values)


0    100
1     87
2     90
Name: Eva, dtype: int64
0    87
1    96
2    70
Name: Wally, dtype: int64
[[ 87 100  94 100  83]
 [ 96  87  77  81  65]
 [ 70  90  90  82  85]]


In [17]:
## Page 266 Self Check

import numpy as np

import pandas as pd

temps = np.random.randint(60, 101, 6)

temperatures = pd.Series(temps)

print(temperatures)

print(temperatures.min())

print(temperatures.max())

print(temperatures.mean())

print(temperatures.describe())



0    67
1    71
2    80
3    67
4    68
5    76
dtype: int32
67
80
71.5
count     6.000000
mean     71.500000
std       5.394442
min      67.000000
25%      67.250000
50%      69.500000
75%      74.750000
max      80.000000
dtype: float64
