# Bambee Garfield Project 4

Name: [Bambee Garfield](https://github.com/Bambee26)

My GitHub [Repos](https://github.com/Bambee26?tab=repositories)

## Task 1 - Series

In [7]:
## Task 1 - Series

import pandas as pd

grades = pd.Series([99, 100, 103, 98, 75])

grades.count()

grades.mean()

grades.min()

grades.max()

grades.std()

grades.describe()


count      5.000000
mean      95.000000
std       11.335784
min       75.000000
25%       98.000000
50%       99.000000
75%      100.000000
max      103.000000
dtype: float64

## Task 2 - Series from Dictionary

In [21]:
import pandas as pd
grades_dict = {'Wally': [87, 96, 70], 'Eva': [100, 87, 90],
                                  'Sam': [94, 77, 90], 'Katie': [100, 81, 82],
                                  'Bob': [83, 65, 85]}
grades = pd.DataFrame(grades_dict)

grades['Eva']


0    100
1     87
2     90
Name: Eva, dtype: int64

In [20]:
grades.Wally

0    87
1    96
2    70
Name: Wally, dtype: int64

In [19]:
grades.values

[[ 87 100  94 100  83]
 [ 96  87  77  81  65]
 [ 70  90  90  82  85]]


In [22]:
## Page 266 Self Check

import numpy as np

import pandas as pd

temps = np.random.randint(60, 101, 6)

temperatures = pd.Series(temps)

temperatures

0    60
1    84
2    73
3    89
4    68
5    91
dtype: int32

In [23]:
temperatures.min()


60

In [24]:
temperatures.max()

91

In [25]:
temperatures.mean()

77.5

In [26]:
temperatures.describe()

count     6.000000
mean     77.500000
std      12.437845
min      60.000000
25%      69.250000
50%      78.500000
75%      87.750000
max      91.000000
dtype: float64